clang-tidy: Fix override errors
The following errors were reported during the clang-tidy enablement
build due to overridden functions not being marked with the override
keyword. The proposed fix is to add the override keyword where it
was missing.

'''
inc/serial_uart_mux.hpp:74:10: error: 'handleEvent' overrides a member function but is not marked 'override' [-Werror
'''

Tested: Verified Build and unit testing.

Change-Id: I999968f538650fb4eefd1702fffcbe49d97d5747
Signed-off-by: Jayanth Othayoth <ojayanth@gmail.com>